# Generated by Django 5.2 on 2025-05-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_full_name_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chronic_diseases',
            field=models.JSONField(blank=True, default=list, verbose_name='만성 질환'),
        ),
    ]
