# Generated by Django 5.2 on 2025-05-06 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='auth_token',
            field=models.CharField(blank=True, help_text='DRF 인증 토큰', max_length=40, null=True, verbose_name='Auth Token'),
        ),
    ]
