# Generated by Django 5.2 on 2025-05-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile_auth_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='auth_token',
            field=models.CharField(blank=True, editable=False, help_text='DRF 인증 토큰', max_length=40, null=True, verbose_name='Auth Token'),
        ),
    ]
