# Generated by Django 5.2 on 2025-04-25 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='약 봉투 사진', upload_to='prescriptions/images/')),
                ('ocr_text', models.TextField(blank=True, help_text='OCR로 읽어온 원문 텍스트')),
                ('pharmacy_name', models.CharField(help_text='약국 이름', max_length=100)),
                ('pharmacy_phone', models.CharField(help_text='약국 전화번호', max_length=20)),
                ('hospital_name', models.CharField(help_text='병원 이름', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='처방전 등록 일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='약 이름', max_length=100)),
                ('frequency_per_day', models.PositiveSmallIntegerField(help_text='1일 투여 횟수')),
                ('dosage', models.CharField(help_text='1회 투여량 (예: "1정", "5ml")', max_length=50)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='prescriptions.prescription')),
            ],
        ),
    ]
