# Generated by Django 5.2 on 2025-04-28 12:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medication',
            name='efficacy',
            field=models.TextField(blank=True, help_text='efcyQesitm(효능)'),
        ),
        migrations.AddField(
            model_name='medication',
            name='image_url',
            field=models.URLField(blank=True, help_text='itemImage(낱알이미지 URL)', max_length=500),
        ),
        migrations.AddField(
            model_name='medication',
            name='interaction',
            field=models.TextField(blank=True, help_text='intrcQesitm(상호작용)'),
        ),
        migrations.AddField(
            model_name='medication',
            name='manufacturer',
            field=models.CharField(blank=True, help_text='entpName(업체명)', max_length=255),
        ),
        migrations.AddField(
            model_name='medication',
            name='precautions',
            field=models.TextField(blank=True, help_text='atpnQesitm(주의사항)'),
        ),
        migrations.AddField(
            model_name='medication',
            name='side_effects',
            field=models.TextField(blank=True, help_text='seQesitm(부작용)'),
        ),
        migrations.AddField(
            model_name='medication',
            name='storage',
            field=models.TextField(blank=True, help_text='depositMethodQesitm(보관법)'),
        ),
        migrations.AddField(
            model_name='medication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='usage',
            field=models.TextField(blank=True, help_text='useMethodQesitm(사용법)'),
        ),
        migrations.AddField(
            model_name='medication',
            name='warning',
            field=models.TextField(blank=True, help_text='atpnWarnQesitm(주의사항 경고)'),
        ),
    ]
