# Generated by Django 5.2 on 2025-04-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_medication_created_at_medication_efficacy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='efficacy',
            field=models.TextField(blank=True, help_text='efcyQesitm(효능)', null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='image_url',
            field=models.URLField(blank=True, help_text='itemImage(낱알이미지 URL)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='interaction',
            field=models.TextField(blank=True, help_text='intrcQesitm(상호작용)', null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='manufacturer',
            field=models.CharField(blank=True, help_text='entpName(업체명)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='precautions',
            field=models.TextField(blank=True, help_text='atpnQesitm(주의사항)', null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='side_effects',
            field=models.TextField(blank=True, help_text='seQesitm(부작용)', null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='storage',
            field=models.TextField(blank=True, help_text='depositMethodQesitm(보관법)', null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='usage',
            field=models.TextField(blank=True, help_text='useMethodQesitm(사용법)', null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='warning',
            field=models.TextField(blank=True, help_text='atpnWarnQesitm(주의사항 경고)', null=True),
        ),
    ]
