# Generated by Django 5.2 on 2025-05-03 11:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0005_remove_prescription_hospital_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None),
        ),
    ]
