# Generated by Django 5.2 on 2025-05-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0006_medication_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='interaction_conflict',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medication',
            name='interaction_conflict_info',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
