# Generated by Django 5.2 on 2025-05-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0008_remove_medication_interaction_conflict_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='allergy_warnings',
            field=models.JSONField(blank=True, default=list, verbose_name='알러지 경고'),
        ),
        migrations.AddField(
            model_name='medication',
            name='condition_warnings',
            field=models.JSONField(blank=True, default=list, verbose_name='지병 경고'),
        ),
    ]
