# Generated by Django 5.2 on 2025-05-05 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0009_medication_allergy_warnings_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Allergy',
        ),
    ]
