# Generated by Django 5.2 on 2025-05-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0010_delete_allergy'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
